version: "2"
services:
  rest:
    build:
      context: .
    ports:
      - 3000:3000
  db:
    image: mysql:8.0
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: