version: "2"
services:
  rest:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 80:80
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: