version: "2"
services:
  rest:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/forums
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forums_development
    # volumes:
    #   - data-volume:/var/lib/mysql
volumes:
  data-volume:
